Repository Chagok-Integrated-for-DevProject/Chagok-Frontend, pull requests merged in 2023-09, with the labels that each got.

#61 :sparkles: Feat: 구글, 카카오 회원 여부 확인 및 회원인 경우 jwt localStorage에 저장
  src/components/common/layout/header/index.tsx
  src/components/signup/index.tsx
  src/components/signup/social/index.tsx
  src/lib/apis/auth.ts
  src/lib/hooks/useAccessToken/index.ts
  src/lib/types/auth.ts
  src/pages/auth/kakao/index.tsx
Labels: 검토 요청 (이상 없으면 Merge), critical

#62 ✨ Feat: 해커톤 상세 api 연동
  public/utils/link.svg
  src/components/common/link/index.tsx
  src/components/hackathons/detail/comment/index.tsx
  src/components/hackathons/detail/comment/item/index.styles.ts
  src/components/hackathons/detail/comment/item/index.tsx
  src/components/hackathons/detail/comment/register/index.styles.ts
  src/components/hackathons/detail/comment/register/index.tsx
  src/components/hackathons/detail/index.tsx
  src/components/hackathons/detail/original/index.styles.ts
  src/components/hackathons/detail/original/index.tsx
  src/components/hackathons/detail/summary/index.styles.ts
  src/components/hackathons/detail/summary/index.tsx
  src/components/signup/social/index.styles.ts
  src/lib/apis/comment.ts
  src/lib/apis/contests.ts
  src/lib/hooks/useCommentMutation/index.ts
  src/lib/hooks/useCommentsQuery/index.ts
  src/lib/hooks/useContestQuery/index.ts
  src/lib/hooks/useInputHooks/index.ts
  src/pages/hackathons/[id]/index.tsx
Labels: 검토 요청 (이상 없으면 Merge), non-critical

#66 :bug: Fix: HomePage 해커톤 카드 DDay에 마감 키워드 추가
  src/components/common/card/hackathons/MainPageCard.tsx
Labels: merge 요청, non-critical

#69 ✨ Feat: 마이 페이지 api 연결
  .github/workflows/Deploy.yml
  next.config.js
  src/components/common/skillContainer/index.tsx
  src/components/hackathons/detail/index.tsx
  src/components/userInfo/UserInfo.tsx
  src/components/userInfo/index.tsx
  src/components/userInfo/profile/index.styles.ts
  src/components/userInfo/profile/index.tsx
  src/components/userInfo/scrab/index.tsx
  src/components/userInfo/skills/index.tsx
  src/lib/apis/userInfo.ts
  src/lib/hooks/useGetMyInfoQuery/index.ts
  src/lib/hooks/useJwtToken/index.ts
  src/lib/hooks/useMyInfoMutation/index.ts
  src/lib/types/userInfo.ts
  src/pages/userInfo/index.tsx
Labels: 검토 요청 (이상 없으면 Merge), non-critical
