Repository Chagok-Integrated-for-DevProject/Chagok-Frontend, pull requests merged in 2023-08, with the labels that each got.

#12 ✨ Feat: 공통 hr 컴포넌트 생성
  src/components/common/Hr.tsx
Labels: merge 요청

#14 💄 Design: 랜딩페이지 프로젝트, 스터디 캐러셀 구현
  jest.setup.js
  package-lock.json
  package.json
  public/mocks/user_profile.svg
  public/showMore.svg
  public/skills/akar-icons_nextjs-fill.svg
  public/skills/akar-icons_php-fill.svg
  public/skills/bxl_unity.svg
  public/skills/devicon_git.svg
  public/skills/devicon_kotlin.svg
  public/skills/devicon_mongodb.svg
  public/skills/devicon_mysql.svg
  public/skills/devicon_nodejs.svg
  public/skills/devicon_spring.svg
  public/skills/devicon_svelte.svg
  public/skills/devicon_typescript.svg
  public/skills/logos_aws.svg
  public/skills/logos_figma.svg
  public/skills/logos_firebase.svg
  public/skills/logos_flutter.svg
  public/skills/logos_go.svg
  public/skills/logos_graphql.svg
  public/skills/logos_java.svg
  public/skills/logos_javascript.svg
  public/skills/logos_jest.svg
  public/skills/logos_kubernetes.svg
  public/skills/logos_nestjs.svg
  public/skills/logos_python.svg
  public/skills/logos_react-1.svg
  public/skills/logos_react.svg
  public/skills/logos_swift.svg
  public/skills/logos_vue.svg
  public/skills/logos_zeplin.svg
  public/skills/simple-icons_express.svg
  public/skills/vscode-icons_file-type-django.svg
  public/skills/vscode-icons_file-type-docker2.svg
  public/top_arrow.svg
  src/components/common/card/projects/index.styles.tsx
  src/components/common/card/projects/index.tsx
  src/components/common/topScrollbtn/index.styles.tsx
  src/components/common/topScrollbtn/index.test.tsx
  src/components/common/topScrollbtn/index.tsx
  src/components/home/carousel/horizontal.styles.tsx
  src/components/home/carousel/horizontal.tsx
  src/components/home/carousel/vertical.tsx
  src/components/home/hackathons/Hottest.tsx
  src/components/home/hackathons/Latest.tsx
  src/components/home/hackathons/index.tsx
  src/components/home/index.styles.ts
  src/components/home/mainBanner/index.tsx
  src/components/home/projects/Hottest.tsx
  src/components/home/projects/Latest.tsx
  src/components/home/projects/index.styles.tsx
  src/components/home/projects/index.tsx
  src/components/home/recommendation/index.tsx
  src/pages/index.tsx
Labels: merge 요청

#19 💄 Design: 전체 공통 BackgroundColor 설정
  src/styles/globalStyles.ts
Labels: merge 요청

#18 🎨 Style: next.cofig.js 세미콜론 누락
  next.config.js
Labels: merge 요청, non-critical

#22 :lipstick: Design: Carousel width 및 padding 수정
  src/components/home/projects/Carousel.styles.ts
  src/components/home/recommendation/Carousel.styles.ts
Labels: merge 요청, non-critical

#24 :package: Chore: bundleAnalyzer 및 svg사용을 위한 세팅
  appspec.yml
  next.config.js
  package-lock.json
  package.json
  scripts/after-install.sh
  scripts/app-start.sh
Labels: merge 요청, non-critical

#25 🚚 Rename: common내 폴더 구조 통일
  ecosystem.config.js
  scripts/after-install.sh
  src/components/common/button/scrab/index.styles.ts
  src/components/common/button/scrab/index.tsx
  src/components/common/button/topScroll/index.styles.ts
  src/components/common/button/topScroll/index.test.tsx
  src/components/common/button/topScroll/index.tsx
  src/components/common/card/hackathons/HackathonPageCard.tsx
  src/components/common/card/hackathons/MainPageCard.tsx
  src/components/common/hr/index.tsx
  src/components/hackathons/list/index.tsx
  src/components/home/hackathons/index.tsx
  src/components/home/recommendation/index.tsx
  src/pages/hackathons/index.tsx
  src/pages/index.tsx
Labels: merge 요청

#27 ✨ Feat: 해커톤 추천 카드 캐러셀 적용
  src/components/hackathons/detail/index.tsx
  src/components/hackathons/recommendation/index.tsx
Labels: merge 요청, non-critical

#28 🐛 Fix: 해커톤 추천 캐러셀 pagination을 위한 css 파일 수정
  scripts/after-install.sh
  src/components/hackathons/recommendation/index.tsx
Labels: merge 요청, non-critical

#31 :sparkles: Feat: ProjectsPage의 SkillSelector구현
  public/bottom_arrow.svg
  public/skills/devicon_c.svg
  scripts/after-install.sh
  src/components/common/layout/header/NavLink.tsx
  src/components/common/layout/header/index.tsx
  src/components/common/mainBanner/index.tsx
  src/components/home/recommendation/Carousel.styles.ts
  src/components/projects/projectList/index.tsx
  src/components/projects/search/PurposeFilter.styles.ts
  src/components/projects/search/PurposeFilter.tsx
  src/components/projects/search/SearchInput.styles.ts
  src/components/projects/search/SearchInput.tsx
  src/components/projects/search/SkillButton.styles.ts
  src/components/projects/search/SkillButton.tsx
  src/components/projects/search/SkillFilter.styles.ts
  src/components/projects/search/SkillFilter.tsx
  src/components/projects/search/index.styles.ts
  src/components/projects/search/index.tsx
  src/components/projects/search/test/SkillFilter.test.tsx
  src/lib/constants/skills.ts
  src/pages/index.tsx
  src/pages/projects/index.tsx
  src/sample.test.tsx
  src/styles/palette.ts
Labels: merge 요청, non-critical

#38 :bug: Fix: 자동 배포 시, 업데이트 된 js번들을 찾지 못하는 문제 해결
  appspec.yml
  scripts/app-start.sh
Labels: merge 요청, non-critical

#40 📦 Chore: msw 초기 설정
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/lib/apis/axiosClient.ts
  src/lib/mocks/broswer.ts
  src/lib/mocks/data/contests.json
  src/lib/mocks/handler.ts
  src/lib/mocks/index.ts
  src/lib/mocks/server.ts
  src/lib/types/hackathon.ts
  src/lib/types/sample.ts
  src/pages/_app.tsx
  src/pages/hackathons/index.tsx
Labels: 검토 요청 (이상 없으면 Merge), critical

#41 :lipstick: Design: 페이지네이션 버튼 및 기능 구현
  src/components/common/button/pagination/index.styles.ts
  src/components/common/button/pagination/index.tsx
  src/components/common/dblArrow/index.tsx
  src/components/common/mainBanner/index.styles.ts
  src/components/common/pagination/index.tsx
  src/components/home/recommendation/Card.styles.ts
  src/components/projects/index.styles.ts
  src/components/projects/index.tsx
  src/components/projects/projectList/index.tsx
  src/components/projects/purposeFilter/index.styles.ts
  src/components/projects/purposeFilter/index.tsx
  src/components/projects/searchInput/index.styles.ts
  src/components/projects/searchInput/index.tsx
  src/components/projects/skillButton/index.styles.ts
  src/components/projects/skillButton/index.tsx
  src/components/projects/skillFilter/index.styles.ts
  src/components/projects/skillFilter/index.tsx
  src/components/projects/test/PurposeFilter.test.tsx
  src/components/projects/test/SearchInput.test.tsx
  src/components/projects/test/SkillButton.test.tsx
  src/components/projects/test/SkillFilter.test.tsx
  src/lib/hooks/useHandlePageNumber/index.test.tsx
  src/lib/hooks/useHandlePageNumber/index.ts
  src/lib/hooks/useInputHooks/index.test.tsx
  src/lib/hooks/useInputHooks/index.ts
  src/lib/utils/pagination.test.ts
  src/lib/utils/pagination.ts
  src/lib/utils/pagination/index.test.ts
  src/lib/utils/pagination/index.ts
  src/pages/projects/index.tsx
Labels: merge 요청, critical

#43 :bug: Fix: 빌드 에러로 인한 500에러 수정
  src/lib/mocks/index.ts
  src/pages/_app.tsx
  tsconfig.json
Labels: merge 요청

#44 💄 Design: 마이 페이지 레이아웃 구현 및 스타일링
  src/components/common/card/hackathons/HackathonPageCard.tsx
  src/components/hackathons/detail/comment/index.tsx
  src/components/userInfo/index.styles.ts
  src/components/userInfo/index.tsx
  src/components/userInfo/profile/index.styles.ts
  src/components/userInfo/profile/index.tsx
  src/components/userInfo/scrab/index.styles.ts
  src/components/userInfo/scrab/index.tsx
  src/components/userInfo/skills/index.styles.ts
  src/components/userInfo/skills/index.tsx
  src/lib/constants/skills.ts
  src/pages/hackathons/index.tsx
  src/styles/breakPoints.ts
  src/styles/palette.ts
Labels: merge 요청, critical

#46 :memo: Docs: README 업데이트(기술 스택 추가)
  README.md
Labels: merge 요청, non-critical

#51 :sparkles: Feat: ProjectPage studies, projects api 연동
  src/components/common/button/pagination/index.test.tsx
  src/components/common/button/pagination/index.tsx
  src/components/common/card/projects/index.styles.tsx
  src/components/common/card/projects/index.tsx
  src/components/common/loading/index.tsx
  src/components/home/projects/Hottest.tsx
  src/components/home/projects/Latest.tsx
  src/components/home/projects/index.tsx
  src/components/home/projects/utils/pickHottestThree.ts
  src/components/home/projects/utils/pickLatestThree.ts
  src/components/projects/Loading/index.tsx
  src/components/projects/index.tsx
  src/components/projects/projectList/index.styles.ts
  src/components/projects/projectList/index.test.tsx
  src/components/projects/projectList/index.tsx
  src/components/projects/purposeFilter/index.test.tsx
  src/components/projects/purposeFilter/index.tsx
  src/components/projects/searchInput/index.test.tsx
  src/components/projects/skillButton/index.test.tsx
  src/components/projects/skillFilter/index.styles.ts
  src/components/projects/skillFilter/index.test.tsx
  src/lib/apis/projects.ts
  src/lib/apis/studies.ts
  src/lib/hooks/useDebounce/index.ts
  src/lib/hooks/useHandlePageNumber/index.test.tsx
  src/lib/hooks/useHandlePageNumber/index.ts
  src/lib/hooks/useProjectsQuery/index.ts
  src/lib/hooks/useStudiesQuery/index.ts
  src/lib/mocks/data/paginationMockData.ts
  src/lib/types/post.ts
  src/lib/utils/converToSkillId/index.ts
  src/lib/utils/converToSkillIdParams/index.ts
  src/pages/index.tsx
  src/pages/projects/index.tsx
Labels: merge 요청, critical

#53 :recycle: Refactor: Pagination 설계 변경 - useHandlePageNumber 삭제
  src/components/home/recommendation/Card.test.tsx
  src/components/projects/projectList/index.test.tsx
  src/components/projects/projectList/index.tsx
  src/lib/hooks/useHandlePageNumber/index.test.tsx
  src/lib/hooks/useHandlePageNumber/index.ts
  src/lib/utils/pagination/index.test.ts
  src/lib/utils/pagination/index.ts
Labels: merge 요청, 검토 요청 (이상 없으면 Merge), critical

#52 :sparkles: Feat: OAuth 구현 (카카오, 구글)
  package-lock.json
  package.json
  public/utils/logout_icon.svg
  public/utils/my_page_icon.svg
  src/components/common/layout/header/index.styles.ts
  src/components/common/layout/header/index.tsx
  src/components/projects/projectList/index.styles.ts
  src/components/signup/social/index.tsx
  src/lib/apis/auth.ts
  src/lib/hooks/useAccessToken/index.ts
  src/pages/_app.tsx
  src/pages/auth/kakao/index.tsx
Labels: merge 요청, non-critical

#55 :lipstick: Design: Header 패딩 축소
  src/components/common/layout/body/Body.styles.ts
  src/components/common/layout/header/index.styles.ts
Labels: non-critical

#59 ✨ Feat: 해커톤 목록 페이지 api 연동
  next.config.js
  src/components/common/arrow/index.tsx
  src/components/common/card/hackathons/HackathonPageCard.tsx
  src/components/common/skillContainer/index.styles.ts
  src/components/hackathons/list/HackathonList.tsx
  src/components/hackathons/list/index.styles.ts
  src/components/hackathons/list/index.tsx
  src/components/hackathons/recommendation/HackathonRecommendList.tsx
  src/components/hackathons/recommendation/index.tsx
  src/components/userInfo/scrab/index.tsx
  src/lib/apis/contests.ts
  src/lib/hooks/useContestsQuery/index.tsx
  src/lib/mocks/handler.ts
  src/lib/types/contest.ts
  src/lib/utils/caculateDDay/index.ts
  src/pages/hackathons/index.tsx
Labels: 검토 요청 (이상 없으면 Merge), non-critical
